### ISSUE TITLE
Add support for callstats from callstats.io

### ISSUE THREAD

**Issue by juberti** [webrtc/apprtc#214]
Looks like an interesting service. Need to see what the privacy policy is, but we should try playing with this on a test instance of AppRTC (i.e. x-dot-apprtc)

-----------------------------------
Directions from callstats.io:
-----------------------------------

1 Include callstats.js.
 script src="https://api.callstats.io/callstats.min.js"

2 Add the app keys to your WebRTC application.

3 Dive into the API documentation.

4 Make the first call.

5 View the live statistics of an ongoing call.

**Comment by vr000m** [comment]
What can we do to help?

**Comment by juberti** [comment]
@vr000m, how much work would it be to get basic call stats wired up? Step #3 above is somewhat open-ended :)

We still need to address the privacy policy question, but would be good to have a handle on the engineering effort here as well.

**Comment by vr000m** [comment]
The very basic requires mainly wiring up 2 APIs after initialising the SDK:
+ AddNewFabric() when peerconnection is created, because it needs access to the PC object to basically attach itself to onNN, onSSC, getStats().
+ sendFabricEvent(): fabricTerminated, audioMute/unmute, videoPause/unpause. 

The callstats.js tries to catch if a PC is explicitly closed or a tab is closed (onbeforeunload), but this is not always perfect. However, in the worst case, the backend removes the call state automatically after 30s of inactivity.

If there are user events like  audioMute, videoPause, wiring up the corresponding [fabricEvents](http://www.callstats.io/api/#enumeration-of-fabricusage) helps, these  show up on the event timeline on the conference details page, helps correlate with the corresponding stats, for example.

---

Optional extra step is wiring up reportError(), this is needed for disambiguating where the call setup failed before negotiation was complete. Since callstats.js cannot access the errorcallbacks of gUM, createOffer, createAnswer, setLD, setRD, calling reportError with the error reason helps narrow down issues related to new version of chrome/ff, munging, etc.

Links to the privacy policy and terms are:
+ http://www.callstats.io/terms/
+ http://www.callstats.io/privacy/

Additionally, there are the cases where

**Comment by juberti** [comment]
@vr000m do you want to make a pull request to add calls to these APIs?

**Comment by vr000m** [comment]
The latest we can get to this is in week 7. @karthikbr82 could you prioritise this within the current iteration? i.e., make a feature complete PR.

**Comment by juberti** [comment]
Not sure I understand - does that mean you can look at this after Feb 15, or before Feb 15?

**Comment by vr000m** [comment]
In week 7, before 19 Feb.

**Comment by juberti** [comment]
OK - sounds good.

**Comment by juberti** [comment]
The kapten has started working on this.
