### ISSUE TITLE
Apprtc not working with Https.

### ISSUE THREAD

**Issue by Priteshchavda** [webrtc/apprtc#233]
Hello,

My domain is https but this apprtc https://url:port is not working only http://url:port working but after update google chrome 47 its not working, how can i start it with ssl.

**Comment by Priteshchavda** [comment]
Hello, Anybody knows about this issue??

**Comment by KaptenJansson** [comment]
Could you provide some (javascript console and devtools network) logs when trying to connect to your AppRTC instance?

**Comment by Priteshchavda** [comment]
Please note simple understanding when i write https://Url:port(/google_appengine/dev_appserver.py /apprtc/out/app_engine/ --host='0.0.0.0' --port=9154{First run this script and after open browser}) and i got SSL error because i dont know where is ssl certificate need to saved in this project. help me i want to start this because webcam is not working with simple HTTP url.

**Comment by KaptenJansson** [comment]
Google app engine does not provide SSL functionality out of the box, you need to setup a SSL tunnel proxy like Stunnel pointing to the AppRTC instance.

Do note however that you can run it locally on localhost:8080 (for development) since Chrome allows getUserMedia from localhost:8080 even if it's HTTP.

**Comment by Priteshchavda** [comment]
Hello, Thanks but i am not understand that how its not working because my server is running in SSL (HTTPS) only this python .py file run and its not open with HTTPS, give me some help url like which setup i need to do to run this in HTTPS. because chrome not allows basic http functionality.

**Comment by KaptenJansson** [comment]
As I mentioned, you can run on HTTP if you start AppRTC on localhost:8080 by starting the instance without any parameters `/google_appengine/dev_appserver.py /apprtc/out/app_engine/` then navigate to http://localhost:8080 in your browser.

If you want to run SSL you need to setup a proxy that forwards your traffic to the AppRTC instance. I recommend stunnel for development (if you use it for production make sure to secure it properly).

Documentation can be found here: https://www.stunnel.org/docs.html
An stunnel guide can be found here: https://www.digitalocean.com/community/tutorials/how-to-set-up-an-ssl-tunnel-using-stunnel-on-ubuntu

Basic steps:
* Create an SSL private key and generate certificates
* Make sure stunnel runs in server modeby adding/setting `client = no` in stunnel.conf.
* Setup a SSL handler in stunnel.conf: 
```[AppRTC]
accept = 443
connect = 127.0.0.1:8080
cert = /etc/stunnel/stunnel.pem
```
* Start the AppRTC instance: `/google_appengine/dev_appserver.py /apprtc/out/app_engine/`
* Browse to https://iptoapprtc
* Do note that the Turn server might not work due to not accessing AppRTC on localhost:8080 directly.

**Comment by Priteshchavda** [comment]
Thanks Brother.

**Comment by jeeva-sil** [comment]
Yes as you said Turn server is not working. I am facing problem as said in [https://github.com/webrtc/apprtc/issues/257](#257) 

Failed to start signaling: Failed to execute 'pushState' on 'History': A history state object with URL 'http://192.168.20.135/r/769453476' cannot be created in a document with origin 'https://192.168.20.135'.

how [https://apprtc.appspot.com/](**https://apprtc.appspot.com/**) is working with secured.

please guide me to achieve this for production.

**Comment by logoff** [comment]
I deployed all the configuration with `stunnel` but then how the AppRTC server will know that it needs to announce rooms with proper socket. Browsers do not accept anymore insecure connections. So how I need to configure AppRTC in concordance with `stunnel`.

**Comment by KaptenJansson** [comment]
It might not work after all but see issue #309 if you can make it work. Do note that this is an unsupported configuration. It's designed to run on Google App Engine with TLS enabled.
