### ISSUE TITLE
demo code deployment: suggestions

### ISSUE THREAD

**Issue by VinceOPS** [webrtc/apprtc#435]
Hi,

First, thanks for this great project. I managed to make it work on my own server, relatively easily.
I would like to propose 2 "enhancements" regarding the documentation (README#deployment [here](https://github.com/webrtc/apprtc#deployment)), as it may save future users some trouble I've been through.

**First**, about the installation of `collider`:
It may be useful to give an extract of a "ready to work" configuration, like this one:

> If go is installed in `/usr/local` and its workspace is created in `<home folder>/go`:

```
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin
export GOPATH=$HOME/go
```
plus, tell the user that the path to TLS/SSL certificates is hard-coded in `main.go`.

And **next**, regarding `coturn`:

The "sample" configuration given for `TURN_SERVER_OVERRIDE` should propose TCP port `3478`, which is coturn's default, instead of `19305` and `19302`.

**Comment by MirkoBonadei** [comment]
Hi @VinceOPS thanks for these suggestions. 

I will try to setup AppRTC on my machine so I can see if I can update the README and then I will publish your suggestions. I will notify you when it is done.

**Comment by VinceOPS** [comment]
Hi @MirkoBonadei 
Thanks for your answer.

I made a few commits since I forked the project, and reported an issue.
Regarding the commits, here are a few of them which might be interesting for the main repository. Please let me know if any PR would be welcome. Otherwise, I'd be glad to help for anything else in this great project (open-source & working WebRTC solutions are not really common, yet).

Proper default TURN ports: https://github.com/VinceOPS/apprtc/commit/2873d6179e81bd5daabf596ca27447cf2d84656f
https://github.com/VinceOPS/apprtc/commit/81d8c8b4fecd10d6f0b98bce6847ca88a9d87504

Relative default paths for collider's certificate, and (optional) ENV variables to define a custom path:
https://github.com/VinceOPS/apprtc/commit/7384582929486e8b2b513ec5e87d1738cdd06d68
https://github.com/VinceOPS/apprtc/commit/db5eb4de1fa7345d0c1a740d81ce701a1344e876

Handle potential exception raised by window.history.pushState:
https://github.com/VinceOPS/apprtc/commit/71e182cd48082d6064bb69ed31c37f4529d7637c

Use new parameter `turnServerOverride` in Chrome app:
https://github.com/VinceOPS/apprtc/commit/6a7102ba11f86fc15ba4870ad33b82c8e9c642b1

Add a new parameter `disableCallstats` (boolean) allowing to disable Callstats initialization:
https://github.com/VinceOPS/apprtc/commit/36d3eac7006b5171036f757a5fbcda6ad9d4dcd3

**Comment by radhey1994** [comment]
Description
I have installed and configured AppRTC, Collider, turn-server successfully.
But getting the blank screen only with AppRTC Logo while accessing the AppRTC URL
Please find the console logs :
~/shubham/apprtc/src/app_engine$ sudo python /usr/lib/google-cloud-sdk/platform/google_appengine/dev_appserver.py /home/intel/shubham1/apprtc/out/app_engine --host=10.223.107.113

INFO 2018-02-15 09:46:33,542 sdk_update_checker.py:231] Checking for updates to the SDK.
INFO 2018-02-15 09:46:36,625 sdk_update_checker.py:247] Update check failed: <urlopen error [Errno 101] Network is unreachable>
INFO 2018-02-15 09:46:36,645 api_server.py:308] Starting API server at: http://localhost:35776
INFO 2018-02-15 09:46:36,651 dispatcher.py:255] Starting module "default" running at: http://10.223.107.113:8080
INFO 2018-02-15 09:46:36,651 admin_server.py:146] Starting admin server at: http://localhost:8000
INFO 2018-02-15 09:46:43,004 apprtc.py:95] Applying media constraints: {'audio': True, 'video': {'mandatory': {}, 'optional': [{'minWidth': '1280'}, {'minHeight': '720'}]}}
WARNING 2018-02-15 09:46:43,006 apprtc.py:139] Invalid or no value returned from memcache, using fallback: null
INFO 2018-02-15 09:46:43,015 module.py:835] default: "GET / HTTP/1.1" 200 8269
INFO 2018-02-15 09:46:43,109 module.py:835] default: "GET /css/main.css HTTP/1.1" 304 -
INFO 2018-02-15 09:46:43,157 module.py:835] default: "GET /js/apprtc.debug.js HTTP/1.1" 404 -
INFO 2018-02-15 09:46:43,679 module.py:835] default: "GET /images/webrtc-icon-192x192.png HTTP/1.1" 200 31806
INFO 2018-02-15 09:46:46,187 apprtc.py:95] Applying media constraints: {'audio': True, 'video': {'mandatory': {}, 'optional': [{'minWidth': '1280'}, {'minHeight': '720'}]}}
WARNING 2018-02-15 09:46:46,189 apprtc.py:139] Invalid or no value returned from memcache, using fallback: null
INFO 2018-02-15 09:46:46,191 module.py:835] default: "GET / HTTP/1.1" 200 8269
INFO 2018-02-15 09:46:46,277 module.py:835] default: "GET /css/main.css HTTP/1.1" 304 -
INFO 2018-02-15 09:46:46,277 module.py:835] default: "GET /js/apprtc.debug.js HTTP/1.1" 404 -
INFO 2018-02-15 09:46:46,731 module.py:835] default: "GET /images/webrtc-icon-192x192.png HTTP/1.1" 200 31806
INFO 2018-02-15 09:55:38,384 apprtc.py:95] Applying media constraints: {'audio': True, 'video': {'mandatory': {}, 'optional': [{'minWidth': '1280'}, {'minHeight': '720'}]}}
WARNING 2018-02-15 09:55:38,386 apprtc.py:139] Invalid or no value returned from memcache, using fallback: null
INFO 2018-02-15 09:55:38,389 module.py:835] default: "GET / HTTP/1.1" 200 8269
INFO 2018-02-15 09:55:39,177 module.py:835] default: "GET /css/main.css HTTP/1.1" 304 -
INFO 2018-02-15 09:55:39,382 module.py:835] default: "GET /js/apprtc.debug.js HTTP/1.1" 404 -
INFO 2018-02-15 09:55:40,274 module.py:835] default: "GET /images/webrtc-icon-192x192.png HTTP/1.1" 200 31806

Have also attached the browser screenshot while accessing AppRTC URL.

image

Please help me out to identify what i am missing??

Thanks in advance

**Comment by KaptenJansson** [comment]
Closing due to age. The last comment can find the solution in #536

**Comment by roshansabale** [comment]
Hello,

@VinceOPS @MirkoBonadei @KaptenJansson 

Is it require stunt server? I have configured three server turn (80/443) collider(8089) and stunt 19302

here is my constant.py file

# Copyright 2015 Google Inc. All Rights Reserved.

"""AppRTC Constants.

This module contains the constants used in AppRTC Python modules.
"""
import os

# Deprecated domains which we should to redirect to REDIRECT_URL.
REDIRECT_DOMAINS =  [
  'apprtc.appspot.com', 'apprtc.webrtc.org', 'www.appr.tc'
]
# URL which we should redirect to if matching in REDIRECT_DOMAINS.
REDIRECT_URL = 'https://appr.tc'

ROOM_MEMCACHE_EXPIRATION_SEC = 60 * 60 * 24
MEMCACHE_RETRY_LIMIT = 100

LOOPBACK_CLIENT_ID = 'LOOPBACK_CLIENT_ID'

# Turn/Stun server override. This allows AppRTC to connect to turn servers
# directly rather than retrieving them from an ICE server provider.
#ICE_SERVER_OVERRIDE = None
# Enable by uncomment below and comment out above, then specify turn and stun
 ICE_SERVER_OVERRIDE  = [
   {
     "urls": [
       "turn:192.168.43.34:80?transport=udp",
       "turn:192.168.43.34:80?transport=tcp"
     ],
     "username": "admin",
     "credential": "admin@123"
   },
   {
     "urls": [
       "stun:192.168.43.34:19302"
     ]
   }
 ]

#ICE_SERVER_BASE_URL = 'https://networktraversal.googleapis.com'
#ICE_SERVER_URL_TEMPLATE = '%s/v1alpha/iceconfig?key=%s'
#ICE_SERVER_API_KEY = os.environ.get('ICE_SERVER_API_KEY')

# Dictionary keys in the collider instance info constant.
WSS_INSTANCE_HOST_KEY = 'host_port_pair'
WSS_INSTANCE_NAME_KEY = 'vm_name'
WSS_INSTANCE_ZONE_KEY = 'zone'
WSS_INSTANCES = [{
    WSS_INSTANCE_HOST_KEY: '192.168.43.34:8089',
#    WSS_INSTANCE_NAME_KEY: 'wsserver-std',
 #   WSS_INSTANCE_ZONE_KEY: 'us-central1-a'
}, {
    WSS_INSTANCE_HOST_KEY: '192.168.43.34:8089',
  #  WSS_INSTANCE_NAME_KEY: 'wsserver-std-2',
   # WSS_INSTANCE_ZONE_KEY: 'us-central1-f'
}]

WSS_HOST_PORT_PAIRS = [ins[WSS_INSTANCE_HOST_KEY] for ins in WSS_INSTANCES]

# memcache key for the active collider host.
WSS_HOST_ACTIVE_HOST_KEY = 'wss_host_active_host'

# Dictionary keys in the collider probing result.
WSS_HOST_IS_UP_KEY = 'is_up'
WSS_HOST_STATUS_CODE_KEY = 'status_code'
WSS_HOST_ERROR_MESSAGE_KEY = 'error_message'

RESPONSE_ERROR = 'ERROR'
RESPONSE_ROOM_FULL = 'FULL'
RESPONSE_UNKNOWN_ROOM = 'UNKNOWN_ROOM'
RESPONSE_UNKNOWN_CLIENT = 'UNKNOWN_CLIENT'
RESPONSE_DUPLICATE_CLIENT = 'DUPLICATE_CLIENT'
RESPONSE_SUCCESS = 'SUCCESS'
RESPONSE_INVALID_REQUEST = 'INVALID_REQUEST'

IS_DEV_SERVER = os.environ.get('APPLICATION_ID', '').startswith('dev')

BIGQUERY_URL = 'https://www.googleapis.com/auth/bigquery'

# Dataset used in production.
BIGQUERY_DATASET_PROD = 'prod'

# Dataset used when running locally.
BIGQUERY_DATASET_LOCAL = 'dev'

# BigQuery table within the dataset.
BIGQUERY_TABLE = 'analytics'
.

> Please check above configuration and update me is it correct

>
