### ISSUE TITLE
Someone can share an instance of apprtc that works?

### ISSUE THREAD

**Issue by joaquingx** [webrtc/apprtc#510]
Hello, 

I was  trying to create a instance of apprtc for like 10 hours and I gave up because I tried like 1000 configurations and I'm don't obtain nothing. There are many persons like me that have this problem and I think that a good solution could be that someone share his configuration files, open ports, packages installed, etc so we can know when we fail in the process. Maybe this is too novice, but a lot of people have this problem.

Regards,
Joaquin

**Comment by KaptenJansson** [comment]
In order to setup AppRTC, lots of knowledge around how Google App Engine apps work are are required in addition to general Node, Python, TURN/STUN, WebRTC and network knowledge. 

Also I know a lot of people are trying to run AppRTC on VM's using dev_appserver.py which is not recommended, it's a development and test server only, not intended for production usage hence we will not support that use case.

In order to help, we need to know what steps you have taken, where you got stuck and what errors you see.
