### ISSUE TITLE
"TURNS is not yet supported" error from callstats

### ISSUE THREAD

**Issue by unmountme** [webrtc/apprtc#520]
**Browsers and versions affected**
FF 55.0 x64

**Description**
Error from callstats and code execution stops. Call doesn't happen.

**Steps to reproduce**
Followed steps under Deployment and enabled TURN_SERVER_OVERRIDE with a working configuration. Same configuration works with other webrtc solutions.

**Expected results**
The error should not happen and code should proceed to make the call happen.

**Actual results**
Error -
TURNS is not yet supported. callstats.min.js:19
Using more than two STUN/TURN servers slows down discovery callstats.min.js:19
TURNS is not yet supported. callstats.min.js:19
Using more than two STUN/TURN servers slows down discovery

When and why this error occurs and how to prevent it. Thanks!

**Comment by KaptenJansson** [comment]
Callstats is now removed.

Please try again.

**Comment by raihan12689** [comment]
Works now !

Thanks.

I'd like your advice on another thing. As an experiment, I converted back end from Python to NodeJS.
I stripped off Bigquery, Memcache, Analytics, Probing and kept minimal features required for a call. Instead of Memcache, using Redis. Did not touch front end JS. I'm posting logs here so you can see the difference.

Python back end, calls working fine, when user 1 joins room, log :
.....................................................
more logs here ...
.....................................................
3.393: Set session description success. apprtc.debug.js:5583 
3.397: Signaling state changed to: have-local-offer apprtc.debug.js:5583 
3.404: C->GAE: {"type":"candidate","label":0,"id":"audio","candidate":"candidate:3573973069 1 udp 2122260223 192.168.0.102 49551 typ host generation 0 ufrag L8aB network-id 1 network-cost 10"} apprtc.debug.js:5583 
3.458: C->GAE: {"type":"candidate","label":0,"id":"audio","candidate":"candidate:1414432505 1 udp 1686052607 103.55.144.47 49551 typ srflx raddr 192.168.0.102 rport 49551 generation 0 ufrag L8aB network-id 1 network-cost 10"} apprtc.debug.js:5583 
3.941: C->GAE: {"type":"candidate","label":0,"id":"audio","candidate":"candidate:3645432079 1 udp 41885439 10.128.0.2 60690 typ relay raddr 103.55.144.47 rport 49551 generation 0 ufrag L8aB network-id 1 network-cost 10"} apprtc.debug.js:5583 
3.942: End of candidates.

Took only 3.942 secs.

My NodeJS back end log when user 1 joins :
.....................................................
more logs here ...
.....................................................
15.526: Set session description success. apprtc.debug.js:5583 
15.526: Signaling state changed to: have-local-offer apprtc.debug.js:5583 
15.540: C->GAE: {"type":"candidate","label":0,"id":"audio","candidate":"candidate:3573973069 1 udp 2122260223 192.168.0.102 55083 typ host generation 0 ufrag FWnD network-id 1 network-cost 10"}
apprtc.debug.js:5583 
15.997: C->GAE: {"type":"candidate","label":0,"id":"audio","candidate":"candidate:1414432505 1 udp 1686052607 103.55.144.42 55083 typ srflx raddr 192.168.0.102 rport 55083 generation 0 ufrag FWnD network-id 1 network-cost 10"} apprtc.debug.js:5583 
21.121: C->GAE: {"type":"candidate","label":0,"id":"audio","candidate":"candidate:3350145135 1 udp 41885695 64.251.31.85 54723 typ relay raddr 103.55.144.42 rport 55083 generation 0 ufrag FWnD network-id 1 network-cost 10"} apprtc.debug.js:5583 
21.123: C->GAE: {"type":"candidate","label":0,"id":"audio","candidate":"candidate:3350145135 1 udp 41885951 64.251.31.85 62823 typ relay raddr 103.55.144.42 rport 55083 generation 0 ufrag FWnD network-id 1 network-cost 10"} apprtc.debug.js:5583 

60.294: End of candidates.

Taking too long. From 21.123 to 60.294 seconds. I wonder what it was doing.

Now, Python back end, calls working fine, user 2 joins room, log :

0.545: Initializing; server= undefined.
apprtc.debug.js:5583 0.545: Initializing; room=653038530.
apprtc.debug.js:5583 0.622: Got access to local media with mediaConstraints:
  '{"audio":true,"video":{"optional":[{"minWidth":"1280"},{"minHeight":"720"}],"mandatory":{}}}'
apprtc.debug.js:5583 0.623: User has granted access to local media.
apprtc.debug.js:5583 0.623: Attaching local stream.
apprtc.debug.js:5583 2.011: Opening signaling channel.
apprtc.debug.js:5583 2.658: Joined the room.
apprtc.debug.js:5583 2.775: Signaling channel opened.
apprtc.debug.js:5583 2.775: Registering signaling channel.
apprtc.debug.js:5583 2.775: Signaling channel registered.
apprtc.debug.js:5583 2.776: Starting signaling.
apprtc.debug.js:5583 2.783: ECDSA certificate generated successfully.
apprtc.debug.js:5583 2.783: Creating RTCPeerConnnection with:
  config: '{"rtcpMuxPolicy":"require","bundlePolicy":"max-bundle","iceServers":[{"username":"xxx","credential":"xxx","urls":["turn:xxx:xxx"]},{"urls":["stun:stun.l.google.com:19302"]}],"certificates":[{}]}';
  constraints: '{"optional":[]}'.
apprtc.debug.js:5583 2.786: Created PeerConnectionClient
apprtc.debug.js:5583 2.786: Adding local stream.
apprtc.debug.js:5583 2.794: No preference on audio send codec.
apprtc.debug.js:5583 2.795: No preference on video send codec.
apprtc.debug.js:5583 2.796: Sending answer to peer.
apprtc.debug.js:5583 2.820: Set remote session description success.
apprtc.debug.js:5583 2.821: Waiting for remote video.
apprtc.debug.js:5583 2.824: No preference on audio receive codec.
apprtc.debug.js:5583 2.824: Prefer video receive codec: VP9
apprtc.debug.js:5583 2.828: C->WSS: {"sdp":"v=0\r\no=- 7257421685353660522 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE audio video\r\na=msid-semantic: WMS QWDBdZqmLq5zgFoe1nD1voL0P2tLXt97yvXB\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:P2kL\r\na=ice-pwd:68Psi77TByAeNsUG5VC76HiR\r\na=ice-options:trickle\r\na=fingerprint:sha-256 04:2A:E8:F9:F1:8D:6C:A9:02:A5:A2:92:31:F8:3B:20:00:D2:C7:8A:63:88:62:1F:CE:2D:35:33:19:CF:74:D0\r\na=setup:active\r\na=mid:audio\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=sendrecv\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=ssrc:3898101878 cname:jTcN3FJjtigX7ef+\r\na=ssrc:3898101878 msid:QWDBdZqmLq5zgFoe1nD1voL0P2tLXt97yvXB 8dba9b2c-a3fa-4b6c-8c15-b133e905cdfd\r\na=ssrc:3898101878 mslabel:QWDBdZqmLq5zgFoe1nD1voL0P2tLXt97yvXB\r\na=ssrc:3898101878 label:8dba9b2c-a3fa-4b6c-8c15-b133e905cdfd\r\nm=video 9 UDP/TLS/RTP/SAVPF 98 96 100 102 127 97 99 101 125\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:P2kL\r\na=ice-pwd:68Psi77TByAeNsUG5VC76HiR\r\na=ice-options:trickle\r\na=fingerprint:sha-256 04:2A:E8:F9:F1:8D:6C:A9:02:A5:A2:92:31:F8:3B:20:00:D2:C7:8A:63:88:62:1F:CE:2D:35:33:19:CF:74:D0\r\na=setup:active\r\na=mid:video\r\na=extmap:2 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 urn:3gpp:video-orientation\r\na=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=sendrecv\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtpmap:100 H264/90000\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:102 red/90000\r\na=rtpmap:127 ulpfec/90000\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:125 rtx/90000\r\na=fmtp:125 apt=102\r\na=ssrc-group:FID 3352738253 1529062255\r\na=ssrc:3352738253 cname:jTcN3FJjtigX7ef+\r\na=ssrc:3352738253 msid:QWDBdZqmLq5zgFoe1nD1voL0P2tLXt97yvXB 56eb96f6-a083-4efa-883a-87af9f5d50e4\r\na=ssrc:3352738253 mslabel:QWDBdZqmLq5zgFoe1nD1voL0P2tLXt97yvXB\r\na=ssrc:3352738253 label:56eb96f6-a083-4efa-883a-87af9f5d50e4\r\na=ssrc:1529062255 cname:jTcN3FJjtigX7ef+\r\na=ssrc:1529062255 msid:QWDBdZqmLq5zgFoe1nD1voL0P2tLXt97yvXB 56eb96f6-a083-4efa-883a-87af9f5d50e4\r\na=ssrc:1529062255 mslabel:QWDBdZqmLq5zgFoe1nD1voL0P2tLXt97yvXB\r\na=ssrc:1529062255 label:56eb96f6-a083-4efa-883a-87af9f5d50e4\r\n","type":"answer"}
apprtc.debug.js:5583 2.829: Remote candidate added successfully.
2apprtc.debug.js:5583 2.830: Remote candidate added successfully.
apprtc.debug.js:5583 2.830: Signaling state changed to: have-remote-offer
apprtc.debug.js:5583 2.857: Remote stream added.
apprtc.debug.js:5583 2.858: Remote stream added.
apprtc.debug.js:5583 2.861: Set session description success.
apprtc.debug.js:5583 2.867: Signaling state changed to: stable
apprtc.debug.js:5583 2.868: ICE connection state changed to: checking
apprtc.debug.js:5583 2.870: C->WSS: {"type":"candidate","label":0,"id":"audio","candidate":"candidate:3573973069 1 udp 2122260223 192.168.0.102 37088 typ host generation 0 ufrag P2kL network-id 1 network-cost 10"}
apprtc.debug.js:5583 2.871: End of candidates.
apprtc.debug.js:5583 3.114: ICE connection state changed to: connected
apprtc.debug.js:5583 3.298: Remote video started; currentTime: 0.114
apprtc.debug.js:5583 3.298: Call setup time: 523ms.
apprtc.debug.js:5583 3.299: reattachMediaStream: [object MediaStream]

Calls working. No issues.

But, my NodeJS back end log when user 2 joins room :

3.263: Initializing; server= xxx.
apprtc.debug.js:5583 3.265: Initializing; room=001780997.
apprtc.debug.js:5583 3.501: Got access to local media with mediaConstraints:
  '{"audio":true,"video":true}'
apprtc.debug.js:5583 3.502: User has granted access to local media.
apprtc.debug.js:5583 3.502: Attaching local stream.
apprtc.debug.js:5583 4.679: Opening signaling channel.
apprtc.debug.js:5583 4.949: Joined the room.
apprtc.debug.js:5583 5.850: Signaling channel opened.
apprtc.debug.js:5583 5.850: Registering signaling channel.
apprtc.debug.js:5583 5.850: Signaling channel registered.
apprtc.debug.js:5583 5.851: Starting signaling.
apprtc.debug.js:5583 5.855: ECDSA certificate generated successfully.
apprtc.debug.js:5583 5.856: Creating RTCPeerConnnection with:
  config: '{"rtcpMuxPolicy":"require","bundlePolicy":"max-bundle","iceServers":[{"username":"xxx","credential":"xxx","urls":["turn:xxx:xxx"]},{"urls":["stun:stun.l.google.com:19302"]}],"certificates":[{}]}';
  constraints: '{"optional":[]}'.
  constraints: '{"optional":[{"DtlsSrtpKeyAgreement":false},{"googDscp":false},{"googIPv6":false}]}'.
apprtc.debug.js:5583 5.858: Created PeerConnectionClient
apprtc.debug.js:5583 5.858: Adding local stream.

It just stops there and does nothing else. 2nd user does not get added to room and call does not happen.

Both Python and NodeJS back end uses same STUN/TURN and Signalling server. 

I'm wondering what am I doing wrong in Node. Thanks!

**Comment by KaptenJansson** [comment]
Closing as the 2nd issue is something else and do not have cycles to debug a converted project.
