### ISSUE TITLE
Remote side video was dropped/paused when there is a long apprtc call [3 hours]

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/apprtc#543]
**Browsers and versions affected**
Chrome Version: 65.0.3325.65 / 10323.30.0 Panther, Candy
OS: Chrome OS

**Steps to reproduce**
(1) Create a peer-peer call between a chrome book and a chrome box https://appr.tc/ [Candy and Panther]
(2) Let the ongoing call active for long period (in my case it was more than 3 hours)

**Expected results**
Video of the remote side works fine. Video quality on either side should be free from glitches.
if this is a limitation it will be nice to inform that the session is expired.

**Actual results**
Remote side video is hanged in both the devices (Panther and candy). The call is still live but the video of the remote side is paused. For example: Video feed of chromebox in chrome book is paused and vice versa. The local video on both these devices continue to work as usual. 

As per the javascript logs: ICE enters a disconnected state which indicates the media connection has been dropped and AppRTC displays the last received video frame. 

Since this is observed in both chrome book and Chrome box. This is likely reproducible in other chrome devices. 

Note: Similar tests were performed in windows machines. Video was quite good until 24 hours. 
https://bugs.chromium.org/p/webrtc/issues/detail?id=8749
https://bugs.chromium.org/p/chromium/issues/detail?id=814290

Logs: [3 hours test.zip](https://github.com/webrtc/apprtc/files/1763590/3.hours.test.zip)

**Comment by KaptenJansson** [comment]
There are some session limitations in the backend and turn server but they should be longer than this. From the logs it's hard to figure whats wrong, just that the media connections dropped, it could be the wifi (AppRTC does not do ice restart hence if the network drops, it will not reconnect like production apps do).

I will close this since there is not much we can do at this point + its not a critical issue, 3 hours is still plenty long.
